### ISSUE TITLE
After pulling the docker image. Branch: 6.X

### ISSUE THREAD

**Issue by alexbgameson** [parkervcp/pterodactyl-daemon-Dockerfile#3]
How do I create and edit core.json within docker?

**Comment by parkervcp** [comment]
You don't. You create it outside of the container.

**Comment by alexbgameson** [comment]
Then how do I get it into the container?

**Comment by parkervcp** [comment]
The docker-compose file has all the volumes. That is what it is for.

**Comment by alexbgameson** [comment]
Okay, But it doesn't create a core.json file in /srv/daemon/config. How am I supposed to configure the node?

**Comment by alexbgameson** [comment]
- "/srv/daemon/config/:/srv/daemon/config/" ## needed to store the config out of the containers This is a default location.

Do I create a core.json file in the main filesystem of the ubuntu install? Like in /srv/daemon/config not in the container?

**Comment by parkervcp** [comment]
Yes, or you lose the daemon token every time you restart.

**Comment by alexbgameson** [comment]
But it didn't work. Its in /srv/daemon/config on my system and it doesn't see the file.

![image](https://user-images.githubusercontent.com/20067071/78316765-7465de80-752e-11ea-99d1-2ab7c7d5378c.png)

**Comment by parkervcp** [comment]
Your screen shot only shows me the file exists. I have no idea what you want from that.

**Comment by alexbgameson** [comment]
I created the file where you told me to. Ran the npm start command in the
docker container and it says that core.json does not exist.

**Comment by parkervcp** [comment]
This container was built to use the docker-compose file. If you don't use that I won't help you.

**Comment by alexbgameson** [comment]
I thought the docker compose file was already used when I created the
container. How do I use it?

**Comment by alexbgameson** [comment]
Does the wings service start automactically? or do I have to do npm start?

**Comment by alexbgameson** [comment]
NVM got it! Thanks for your help.

**Comment by alexbgameson** [comment]
Now I am getting this error:

Starting rsa-key-20181209_ptero_1 ... error
ERROR: for rsa-key-20181209_ptero_1  Cannot start service ptero: error while creating mount source path '/var/lib/docker/c
ontainers': mkdir /var/lib/docker: read-only file system
ERROR: for ptero  Cannot start service ptero: error while creating mount source path '/var/lib/docker/containers': mkdir /
var/lib/docker: read-only file system
ERROR: Encountered errors while bringing up the project.

**Comment by parkervcp** [comment]
You have another docker network that is overlapping the pterodactyl one. you can run `docker network ls` to see what ones are there.

Honestly This isn't the place for me to teach you how docker works...

**Comment by alexbgameson** [comment]
Nvm. Figured it out. Sorry to be a bother. One last question. Is the daemon runnable in a swarm? or will that cause issues?

**Comment by alexbgameson** [comment]
As a sort of load balancer

**Comment by parkervcp** [comment]
You cannot run the daemon with swarm.
